#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WINotify
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CLARIFYDW")]
	public partial class CaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFACT_CASE(FACT_CASE instance);
    partial void UpdateFACT_CASE(FACT_CASE instance);
    partial void DeleteFACT_CASE(FACT_CASE instance);
    partial void InsertFACT_CASECLOSE(FACT_CASECLOSE instance);
    partial void UpdateFACT_CASECLOSE(FACT_CASECLOSE instance);
    partial void DeleteFACT_CASECLOSE(FACT_CASECLOSE instance);
    partial void InsertDIM_PRODUCT(DIM_PRODUCT instance);
    partial void UpdateDIM_PRODUCT(DIM_PRODUCT instance);
    partial void DeleteDIM_PRODUCT(DIM_PRODUCT instance);
    partial void InsertDIM_SITE(DIM_SITE instance);
    partial void UpdateDIM_SITE(DIM_SITE instance);
    partial void DeleteDIM_SITE(DIM_SITE instance);
    partial void InsertDIM_CASETYPE(DIM_CASETYPE instance);
    partial void UpdateDIM_CASETYPE(DIM_CASETYPE instance);
    partial void DeleteDIM_CASETYPE(DIM_CASETYPE instance);
    partial void InsertDIM_USER(DIM_USER instance);
    partial void UpdateDIM_USER(DIM_USER instance);
    partial void DeleteDIM_USER(DIM_USER instance);
    partial void InsertDIM_CONTACT(DIM_CONTACT instance);
    partial void UpdateDIM_CONTACT(DIM_CONTACT instance);
    partial void DeleteDIM_CONTACT(DIM_CONTACT instance);
    #endregion
		
		public CaseDataContext() : 
				base(global::WINotify.Properties.Settings.Default.CLARIFYDWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FACT_CASE> FACT_CASEs
		{
			get
			{
				return this.GetTable<FACT_CASE>();
			}
		}
		
		public System.Data.Linq.Table<FACT_CASECLOSE> FACT_CASECLOSEs
		{
			get
			{
				return this.GetTable<FACT_CASECLOSE>();
			}
		}
		
		public System.Data.Linq.Table<DIM_PRODUCT> DIM_PRODUCTs
		{
			get
			{
				return this.GetTable<DIM_PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<DIM_SITE> DIM_SITEs
		{
			get
			{
				return this.GetTable<DIM_SITE>();
			}
		}
		
		public System.Data.Linq.Table<DIM_CASETYPE> DIM_CASETYPEs
		{
			get
			{
				return this.GetTable<DIM_CASETYPE>();
			}
		}
		
		public System.Data.Linq.Table<DIM_USER> DIM_USERs
		{
			get
			{
				return this.GetTable<DIM_USER>();
			}
		}
		
		public System.Data.Linq.Table<DIM_CONTACT> DIM_CONTACTs
		{
			get
			{
				return this.GetTable<DIM_CONTACT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACT_CASE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class FACT_CASE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private string _CaseNumber;
		
		private string _TopicCode;
		
		private string _Condition;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private System.Nullable<int> _CaseAge;
		
		private System.Nullable<int> _DateAddedID;
		
		private System.Nullable<bool> _CustomerSupport;
		
		private System.Nullable<int> _ProductID;
		
		private System.Nullable<int> _SiteID;
		
		private System.Nullable<int> _CaseTypeID;
		
		private System.Nullable<int> _CaseStatusID;
		
		private System.Nullable<int> _CaseSeverityID;
		
		private System.Nullable<int> _ContactID;
		
		private System.Nullable<int> _OwnerUserID;
		
		private System.Nullable<int> _CreatorUserID;
		
		private System.Nullable<int> _ETLControlID;
		
		private string _TAMStatus;
		
		private string _DSSTYPE;
		
		private string _CCList1;
		
		private string _CCList2;
		
		private System.Nullable<int> _CRID;
		
		private string _WIPBIN;
		
		private string _CQTICKET;
		
		private System.Nullable<int> _WorkItem;
		
		private string _ClientTrackingID;
		
		private string _CaseHistory;
		
		private string _SolutionNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnCaseNumberChanging(string value);
    partial void OnCaseNumberChanged();
    partial void OnTopicCodeChanging(string value);
    partial void OnTopicCodeChanged();
    partial void OnConditionChanging(string value);
    partial void OnConditionChanged();
    partial void OnDateAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateAddedChanged();
    partial void OnCaseAgeChanging(System.Nullable<int> value);
    partial void OnCaseAgeChanged();
    partial void OnDateAddedIDChanging(System.Nullable<int> value);
    partial void OnDateAddedIDChanged();
    partial void OnCustomerSupportChanging(System.Nullable<bool> value);
    partial void OnCustomerSupportChanged();
    partial void OnProductIDChanging(System.Nullable<int> value);
    partial void OnProductIDChanged();
    partial void OnSiteIDChanging(System.Nullable<int> value);
    partial void OnSiteIDChanged();
    partial void OnCaseTypeIDChanging(System.Nullable<int> value);
    partial void OnCaseTypeIDChanged();
    partial void OnCaseStatusIDChanging(System.Nullable<int> value);
    partial void OnCaseStatusIDChanged();
    partial void OnCaseSeverityIDChanging(System.Nullable<int> value);
    partial void OnCaseSeverityIDChanged();
    partial void OnContactIDChanging(System.Nullable<int> value);
    partial void OnContactIDChanged();
    partial void OnOwnerUserIDChanging(System.Nullable<int> value);
    partial void OnOwnerUserIDChanged();
    partial void OnCreatorUserIDChanging(System.Nullable<int> value);
    partial void OnCreatorUserIDChanged();
    partial void OnETLControlIDChanging(System.Nullable<int> value);
    partial void OnETLControlIDChanged();
    partial void OnTAMStatusChanging(string value);
    partial void OnTAMStatusChanged();
    partial void OnDSSTYPEChanging(string value);
    partial void OnDSSTYPEChanged();
    partial void OnCCList1Changing(string value);
    partial void OnCCList1Changed();
    partial void OnCCList2Changing(string value);
    partial void OnCCList2Changed();
    partial void OnCRIDChanging(System.Nullable<int> value);
    partial void OnCRIDChanged();
    partial void OnWIPBINChanging(string value);
    partial void OnWIPBINChanged();
    partial void OnCQTICKETChanging(string value);
    partial void OnCQTICKETChanged();
    partial void OnWorkItemChanging(System.Nullable<int> value);
    partial void OnWorkItemChanged();
    partial void OnClientTrackingIDChanging(string value);
    partial void OnClientTrackingIDChanged();
    partial void OnCaseHistoryChanging(string value);
    partial void OnCaseHistoryChanged();
    partial void OnSolutionNumberChanging(string value);
    partial void OnSolutionNumberChanged();
    #endregion
		
		public FACT_CASE()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseNumber", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string CaseNumber
		{
			get
			{
				return this._CaseNumber;
			}
			set
			{
				if ((this._CaseNumber != value))
				{
					this.OnCaseNumberChanging(value);
					this.SendPropertyChanging();
					this._CaseNumber = value;
					this.SendPropertyChanged("CaseNumber");
					this.OnCaseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopicCode", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string TopicCode
		{
			get
			{
				return this._TopicCode;
			}
			set
			{
				if ((this._TopicCode != value))
				{
					this.OnTopicCodeChanging(value);
					this.SendPropertyChanging();
					this._TopicCode = value;
					this.SendPropertyChanged("TopicCode");
					this.OnTopicCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condition", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Condition
		{
			get
			{
				return this._Condition;
			}
			set
			{
				if ((this._Condition != value))
				{
					this.OnConditionChanging(value);
					this.SendPropertyChanging();
					this._Condition = value;
					this.SendPropertyChanged("Condition");
					this.OnConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseAge", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> CaseAge
		{
			get
			{
				return this._CaseAge;
			}
			set
			{
				if ((this._CaseAge != value))
				{
					this.OnCaseAgeChanging(value);
					this.SendPropertyChanging();
					this._CaseAge = value;
					this.SendPropertyChanged("CaseAge");
					this.OnCaseAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAddedID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> DateAddedID
		{
			get
			{
				return this._DateAddedID;
			}
			set
			{
				if ((this._DateAddedID != value))
				{
					this.OnDateAddedIDChanging(value);
					this.SendPropertyChanging();
					this._DateAddedID = value;
					this.SendPropertyChanged("DateAddedID");
					this.OnDateAddedIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerSupport", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<bool> CustomerSupport
		{
			get
			{
				return this._CustomerSupport;
			}
			set
			{
				if ((this._CustomerSupport != value))
				{
					this.OnCustomerSupportChanging(value);
					this.SendPropertyChanging();
					this._CustomerSupport = value;
					this.SendPropertyChanged("CustomerSupport");
					this.OnCustomerSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseTypeID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<int> CaseTypeID
		{
			get
			{
				return this._CaseTypeID;
			}
			set
			{
				if ((this._CaseTypeID != value))
				{
					this.OnCaseTypeIDChanging(value);
					this.SendPropertyChanging();
					this._CaseTypeID = value;
					this.SendPropertyChanged("CaseTypeID");
					this.OnCaseTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseStatusID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> CaseStatusID
		{
			get
			{
				return this._CaseStatusID;
			}
			set
			{
				if ((this._CaseStatusID != value))
				{
					this.OnCaseStatusIDChanging(value);
					this.SendPropertyChanging();
					this._CaseStatusID = value;
					this.SendPropertyChanged("CaseStatusID");
					this.OnCaseStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseSeverityID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> CaseSeverityID
		{
			get
			{
				return this._CaseSeverityID;
			}
			set
			{
				if ((this._CaseSeverityID != value))
				{
					this.OnCaseSeverityIDChanging(value);
					this.SendPropertyChanging();
					this._CaseSeverityID = value;
					this.SendPropertyChanged("CaseSeverityID");
					this.OnCaseSeverityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this.OnContactIDChanging(value);
					this.SendPropertyChanging();
					this._ContactID = value;
					this.SendPropertyChanged("ContactID");
					this.OnContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerUserID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<int> OwnerUserID
		{
			get
			{
				return this._OwnerUserID;
			}
			set
			{
				if ((this._OwnerUserID != value))
				{
					this.OnOwnerUserIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerUserID = value;
					this.SendPropertyChanged("OwnerUserID");
					this.OnOwnerUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatorUserID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> CreatorUserID
		{
			get
			{
				return this._CreatorUserID;
			}
			set
			{
				if ((this._CreatorUserID != value))
				{
					this.OnCreatorUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatorUserID = value;
					this.SendPropertyChanged("CreatorUserID");
					this.OnCreatorUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETLControlID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<int> ETLControlID
		{
			get
			{
				return this._ETLControlID;
			}
			set
			{
				if ((this._ETLControlID != value))
				{
					this.OnETLControlIDChanging(value);
					this.SendPropertyChanging();
					this._ETLControlID = value;
					this.SendPropertyChanged("ETLControlID");
					this.OnETLControlIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAMStatus", DbType="NVarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public string TAMStatus
		{
			get
			{
				return this._TAMStatus;
			}
			set
			{
				if ((this._TAMStatus != value))
				{
					this.OnTAMStatusChanging(value);
					this.SendPropertyChanging();
					this._TAMStatus = value;
					this.SendPropertyChanged("TAMStatus");
					this.OnTAMStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSSTYPE", DbType="Char(11)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public string DSSTYPE
		{
			get
			{
				return this._DSSTYPE;
			}
			set
			{
				if ((this._DSSTYPE != value))
				{
					this.OnDSSTYPEChanging(value);
					this.SendPropertyChanging();
					this._DSSTYPE = value;
					this.SendPropertyChanged("DSSTYPE");
					this.OnDSSTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCList1", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string CCList1
		{
			get
			{
				return this._CCList1;
			}
			set
			{
				if ((this._CCList1 != value))
				{
					this.OnCCList1Changing(value);
					this.SendPropertyChanging();
					this._CCList1 = value;
					this.SendPropertyChanged("CCList1");
					this.OnCCList1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCList2", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public string CCList2
		{
			get
			{
				return this._CCList2;
			}
			set
			{
				if ((this._CCList2 != value))
				{
					this.OnCCList2Changing(value);
					this.SendPropertyChanging();
					this._CCList2 = value;
					this.SendPropertyChanged("CCList2");
					this.OnCCList2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public System.Nullable<int> CRID
		{
			get
			{
				return this._CRID;
			}
			set
			{
				if ((this._CRID != value))
				{
					this.OnCRIDChanging(value);
					this.SendPropertyChanging();
					this._CRID = value;
					this.SendPropertyChanged("CRID");
					this.OnCRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIPBIN", DbType="VarChar(24)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public string WIPBIN
		{
			get
			{
				return this._WIPBIN;
			}
			set
			{
				if ((this._WIPBIN != value))
				{
					this.OnWIPBINChanging(value);
					this.SendPropertyChanging();
					this._WIPBIN = value;
					this.SendPropertyChanged("WIPBIN");
					this.OnWIPBINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CQTICKET", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=25)]
		public string CQTICKET
		{
			get
			{
				return this._CQTICKET;
			}
			set
			{
				if ((this._CQTICKET != value))
				{
					this.OnCQTICKETChanging(value);
					this.SendPropertyChanging();
					this._CQTICKET = value;
					this.SendPropertyChanged("CQTICKET");
					this.OnCQTICKETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkItem", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=26)]
		public System.Nullable<int> WorkItem
		{
			get
			{
				return this._WorkItem;
			}
			set
			{
				if ((this._WorkItem != value))
				{
					this.OnWorkItemChanging(value);
					this.SendPropertyChanging();
					this._WorkItem = value;
					this.SendPropertyChanged("WorkItem");
					this.OnWorkItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientTrackingID", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=27)]
		public string ClientTrackingID
		{
			get
			{
				return this._ClientTrackingID;
			}
			set
			{
				if ((this._ClientTrackingID != value))
				{
					this.OnClientTrackingIDChanging(value);
					this.SendPropertyChanging();
					this._ClientTrackingID = value;
					this.SendPropertyChanged("ClientTrackingID");
					this.OnClientTrackingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseHistory", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=28)]
		public string CaseHistory
		{
			get
			{
				return this._CaseHistory;
			}
			set
			{
				if ((this._CaseHistory != value))
				{
					this.OnCaseHistoryChanging(value);
					this.SendPropertyChanging();
					this._CaseHistory = value;
					this.SendPropertyChanged("CaseHistory");
					this.OnCaseHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SolutionNumber", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=29)]
		public string SolutionNumber
		{
			get
			{
				return this._SolutionNumber;
			}
			set
			{
				if ((this._SolutionNumber != value))
				{
					this.OnSolutionNumberChanging(value);
					this.SendPropertyChanging();
					this._SolutionNumber = value;
					this.SendPropertyChanged("SolutionNumber");
					this.OnSolutionNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACT_CASECLOSE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class FACT_CASECLOSE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _PhoneTime;
		
		private System.Nullable<int> _ResearchTime;
		
		private System.Nullable<int> _CaseID;
		
		private System.Nullable<int> _CloserUserID;
		
		private System.Nullable<int> _DateClosedID;
		
		private System.Nullable<int> _ResolutionID;
		
		private System.Nullable<int> _ETLControlID;
		
		private string _CloseCategory;
		
		private string _CloseSubcategory;
		
		private string _CloseResolution;
		
		private string _CloseRootCause;
		
		private System.Nullable<int> _ClosePerformance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPhoneTimeChanging(System.Nullable<int> value);
    partial void OnPhoneTimeChanged();
    partial void OnResearchTimeChanging(System.Nullable<int> value);
    partial void OnResearchTimeChanged();
    partial void OnCaseIDChanging(System.Nullable<int> value);
    partial void OnCaseIDChanged();
    partial void OnCloserUserIDChanging(System.Nullable<int> value);
    partial void OnCloserUserIDChanged();
    partial void OnDateClosedIDChanging(System.Nullable<int> value);
    partial void OnDateClosedIDChanged();
    partial void OnResolutionIDChanging(System.Nullable<int> value);
    partial void OnResolutionIDChanged();
    partial void OnETLControlIDChanging(System.Nullable<int> value);
    partial void OnETLControlIDChanged();
    partial void OnCloseCategoryChanging(string value);
    partial void OnCloseCategoryChanged();
    partial void OnCloseSubcategoryChanging(string value);
    partial void OnCloseSubcategoryChanged();
    partial void OnCloseResolutionChanging(string value);
    partial void OnCloseResolutionChanged();
    partial void OnCloseRootCauseChanging(string value);
    partial void OnCloseRootCauseChanged();
    partial void OnClosePerformanceChanging(System.Nullable<int> value);
    partial void OnClosePerformanceChanged();
    #endregion
		
		public FACT_CASECLOSE()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneTime", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> PhoneTime
		{
			get
			{
				return this._PhoneTime;
			}
			set
			{
				if ((this._PhoneTime != value))
				{
					this.OnPhoneTimeChanging(value);
					this.SendPropertyChanging();
					this._PhoneTime = value;
					this.SendPropertyChanged("PhoneTime");
					this.OnPhoneTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResearchTime", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> ResearchTime
		{
			get
			{
				return this._ResearchTime;
			}
			set
			{
				if ((this._ResearchTime != value))
				{
					this.OnResearchTimeChanging(value);
					this.SendPropertyChanging();
					this._ResearchTime = value;
					this.SendPropertyChanged("ResearchTime");
					this.OnResearchTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<int> CaseID
		{
			get
			{
				return this._CaseID;
			}
			set
			{
				if ((this._CaseID != value))
				{
					this.OnCaseIDChanging(value);
					this.SendPropertyChanging();
					this._CaseID = value;
					this.SendPropertyChanged("CaseID");
					this.OnCaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloserUserID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> CloserUserID
		{
			get
			{
				return this._CloserUserID;
			}
			set
			{
				if ((this._CloserUserID != value))
				{
					this.OnCloserUserIDChanging(value);
					this.SendPropertyChanging();
					this._CloserUserID = value;
					this.SendPropertyChanged("CloserUserID");
					this.OnCloserUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateClosedID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> DateClosedID
		{
			get
			{
				return this._DateClosedID;
			}
			set
			{
				if ((this._DateClosedID != value))
				{
					this.OnDateClosedIDChanging(value);
					this.SendPropertyChanging();
					this._DateClosedID = value;
					this.SendPropertyChanged("DateClosedID");
					this.OnDateClosedIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResolutionID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> ResolutionID
		{
			get
			{
				return this._ResolutionID;
			}
			set
			{
				if ((this._ResolutionID != value))
				{
					this.OnResolutionIDChanging(value);
					this.SendPropertyChanging();
					this._ResolutionID = value;
					this.SendPropertyChanged("ResolutionID");
					this.OnResolutionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETLControlID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> ETLControlID
		{
			get
			{
				return this._ETLControlID;
			}
			set
			{
				if ((this._ETLControlID != value))
				{
					this.OnETLControlIDChanging(value);
					this.SendPropertyChanging();
					this._ETLControlID = value;
					this.SendPropertyChanged("ETLControlID");
					this.OnETLControlIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseCategory", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string CloseCategory
		{
			get
			{
				return this._CloseCategory;
			}
			set
			{
				if ((this._CloseCategory != value))
				{
					this.OnCloseCategoryChanging(value);
					this.SendPropertyChanging();
					this._CloseCategory = value;
					this.SendPropertyChanged("CloseCategory");
					this.OnCloseCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseSubcategory", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string CloseSubcategory
		{
			get
			{
				return this._CloseSubcategory;
			}
			set
			{
				if ((this._CloseSubcategory != value))
				{
					this.OnCloseSubcategoryChanging(value);
					this.SendPropertyChanging();
					this._CloseSubcategory = value;
					this.SendPropertyChanged("CloseSubcategory");
					this.OnCloseSubcategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseResolution", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string CloseResolution
		{
			get
			{
				return this._CloseResolution;
			}
			set
			{
				if ((this._CloseResolution != value))
				{
					this.OnCloseResolutionChanging(value);
					this.SendPropertyChanging();
					this._CloseResolution = value;
					this.SendPropertyChanged("CloseResolution");
					this.OnCloseResolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseRootCause", DbType="VarChar(60)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string CloseRootCause
		{
			get
			{
				return this._CloseRootCause;
			}
			set
			{
				if ((this._CloseRootCause != value))
				{
					this.OnCloseRootCauseChanging(value);
					this.SendPropertyChanging();
					this._CloseRootCause = value;
					this.SendPropertyChanged("CloseRootCause");
					this.OnCloseRootCauseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosePerformance", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> ClosePerformance
		{
			get
			{
				return this._ClosePerformance;
			}
			set
			{
				if ((this._ClosePerformance != value))
				{
					this.OnClosePerformanceChanging(value);
					this.SendPropertyChanging();
					this._ClosePerformance = value;
					this.SendPropertyChanged("ClosePerformance");
					this.OnClosePerformanceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_PRODUCT")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DIM_PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SKU;
		
		private string _Description;
		
		private string _Line;
		
		private string _Family;
		
		private string _Type;
		
		private string _Version;
		
		private string _Maintenance;
		
		private string _SerialNumber;
		
		private System.Nullable<int> _NumberOfUsers;
		
		private string _Notes;
		
		private string _Status;
		
		private System.Nullable<int> _ShipDateID;
		
		private System.Nullable<int> _ETLControlID;
		
		private System.Nullable<int> _SiteID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnLineChanging(string value);
    partial void OnLineChanged();
    partial void OnFamilyChanging(string value);
    partial void OnFamilyChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnMaintenanceChanging(string value);
    partial void OnMaintenanceChanged();
    partial void OnSerialNumberChanging(string value);
    partial void OnSerialNumberChanged();
    partial void OnNumberOfUsersChanging(System.Nullable<int> value);
    partial void OnNumberOfUsersChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnShipDateIDChanging(System.Nullable<int> value);
    partial void OnShipDateIDChanged();
    partial void OnETLControlIDChanging(System.Nullable<int> value);
    partial void OnETLControlIDChanged();
    partial void OnSiteIDChanging(System.Nullable<int> value);
    partial void OnSiteIDChanged();
    #endregion
		
		public DIM_PRODUCT()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Line
		{
			get
			{
				return this._Line;
			}
			set
			{
				if ((this._Line != value))
				{
					this.OnLineChanging(value);
					this.SendPropertyChanging();
					this._Line = value;
					this.SendPropertyChanged("Line");
					this.OnLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				if ((this._Family != value))
				{
					this.OnFamilyChanging(value);
					this.SendPropertyChanging();
					this._Family = value;
					this.SendPropertyChanged("Family");
					this.OnFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maintenance", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Maintenance
		{
			get
			{
				return this._Maintenance;
			}
			set
			{
				if ((this._Maintenance != value))
				{
					this.OnMaintenanceChanging(value);
					this.SendPropertyChanging();
					this._Maintenance = value;
					this.SendPropertyChanged("Maintenance");
					this.OnMaintenanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this.OnSerialNumberChanging(value);
					this.SendPropertyChanging();
					this._SerialNumber = value;
					this.SendPropertyChanged("SerialNumber");
					this.OnSerialNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfUsers", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> NumberOfUsers
		{
			get
			{
				return this._NumberOfUsers;
			}
			set
			{
				if ((this._NumberOfUsers != value))
				{
					this.OnNumberOfUsersChanging(value);
					this.SendPropertyChanging();
					this._NumberOfUsers = value;
					this.SendPropertyChanged("NumberOfUsers");
					this.OnNumberOfUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(3)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipDateID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> ShipDateID
		{
			get
			{
				return this._ShipDateID;
			}
			set
			{
				if ((this._ShipDateID != value))
				{
					this.OnShipDateIDChanging(value);
					this.SendPropertyChanging();
					this._ShipDateID = value;
					this.SendPropertyChanged("ShipDateID");
					this.OnShipDateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETLControlID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> ETLControlID
		{
			get
			{
				return this._ETLControlID;
			}
			set
			{
				if ((this._ETLControlID != value))
				{
					this.OnETLControlIDChanging(value);
					this.SendPropertyChanging();
					this._ETLControlID = value;
					this.SendPropertyChanged("ETLControlID");
					this.OnETLControlIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_SITE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DIM_SITE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SiteID;
		
		private string _Name;
		
		private string _Class;
		
		private string _Division;
		
		private string _Affiliation;
		
		private string _SupportSite;
		
		private string _Type;
		
		private string _ABS;
		
		private string _Alias;
		
		private string _Notes;
		
		private string _PreviousSystem;
		
		private System.Nullable<int> _Status;
		
		private string _PrimaryAddressLine1;
		
		private string _PrimaryAddressLine2;
		
		private string _PrimaryAddressLine3;
		
		private string _PrimaryCity;
		
		private string _PrimaryState;
		
		private string _PrimaryZIP;
		
		private string _PrimaryCountry;
		
		private string _BillingAddressLine1;
		
		private string _BillingAddressLine2;
		
		private string _BillingAddressLine3;
		
		private string _BillingCity;
		
		private string _BillingState;
		
		private string _BillingZIP;
		
		private string _BillingCountry;
		
		private string _ShippingAddressLine1;
		
		private string _ShippingAddressLine2;
		
		private string _ShippingAddressLine3;
		
		private string _ShippingCity;
		
		private string _ShippingState;
		
		private string _ShippingZIP;
		
		private string _ShippingCountry;
		
		private System.Nullable<int> _ClientSinceDateID;
		
		private System.Nullable<int> _ParentSiteID;
		
		private System.Nullable<int> _EBusSiteID;
		
		private string _BusinessUnit;
		
		private System.Nullable<bool> _bbpsauthenticated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSiteIDChanging(string value);
    partial void OnSiteIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    partial void OnDivisionChanging(string value);
    partial void OnDivisionChanged();
    partial void OnAffiliationChanging(string value);
    partial void OnAffiliationChanged();
    partial void OnSupportSiteChanging(string value);
    partial void OnSupportSiteChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnABSChanging(string value);
    partial void OnABSChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnPreviousSystemChanging(string value);
    partial void OnPreviousSystemChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnPrimaryAddressLine1Changing(string value);
    partial void OnPrimaryAddressLine1Changed();
    partial void OnPrimaryAddressLine2Changing(string value);
    partial void OnPrimaryAddressLine2Changed();
    partial void OnPrimaryAddressLine3Changing(string value);
    partial void OnPrimaryAddressLine3Changed();
    partial void OnPrimaryCityChanging(string value);
    partial void OnPrimaryCityChanged();
    partial void OnPrimaryStateChanging(string value);
    partial void OnPrimaryStateChanged();
    partial void OnPrimaryZIPChanging(string value);
    partial void OnPrimaryZIPChanged();
    partial void OnPrimaryCountryChanging(string value);
    partial void OnPrimaryCountryChanged();
    partial void OnBillingAddressLine1Changing(string value);
    partial void OnBillingAddressLine1Changed();
    partial void OnBillingAddressLine2Changing(string value);
    partial void OnBillingAddressLine2Changed();
    partial void OnBillingAddressLine3Changing(string value);
    partial void OnBillingAddressLine3Changed();
    partial void OnBillingCityChanging(string value);
    partial void OnBillingCityChanged();
    partial void OnBillingStateChanging(string value);
    partial void OnBillingStateChanged();
    partial void OnBillingZIPChanging(string value);
    partial void OnBillingZIPChanged();
    partial void OnBillingCountryChanging(string value);
    partial void OnBillingCountryChanged();
    partial void OnShippingAddressLine1Changing(string value);
    partial void OnShippingAddressLine1Changed();
    partial void OnShippingAddressLine2Changing(string value);
    partial void OnShippingAddressLine2Changed();
    partial void OnShippingAddressLine3Changing(string value);
    partial void OnShippingAddressLine3Changed();
    partial void OnShippingCityChanging(string value);
    partial void OnShippingCityChanged();
    partial void OnShippingStateChanging(string value);
    partial void OnShippingStateChanged();
    partial void OnShippingZIPChanging(string value);
    partial void OnShippingZIPChanged();
    partial void OnShippingCountryChanging(string value);
    partial void OnShippingCountryChanged();
    partial void OnClientSinceDateIDChanging(System.Nullable<int> value);
    partial void OnClientSinceDateIDChanged();
    partial void OnParentSiteIDChanging(System.Nullable<int> value);
    partial void OnParentSiteIDChanged();
    partial void OnEBusSiteIDChanging(System.Nullable<int> value);
    partial void OnEBusSiteIDChanged();
    partial void OnBusinessUnitChanging(string value);
    partial void OnBusinessUnitChanged();
    partial void OnbbpsauthenticatedChanging(System.Nullable<bool> value);
    partial void OnbbpsauthenticatedChanged();
    #endregion
		
		public DIM_SITE()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Affiliation", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Affiliation
		{
			get
			{
				return this._Affiliation;
			}
			set
			{
				if ((this._Affiliation != value))
				{
					this.OnAffiliationChanging(value);
					this.SendPropertyChanging();
					this._Affiliation = value;
					this.SendPropertyChanged("Affiliation");
					this.OnAffiliationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportSite", DbType="Char(4)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string SupportSite
		{
			get
			{
				return this._SupportSite;
			}
			set
			{
				if ((this._SupportSite != value))
				{
					this.OnSupportSiteChanging(value);
					this.SendPropertyChanging();
					this._SupportSite = value;
					this.SendPropertyChanged("SupportSite");
					this.OnSupportSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABS", DbType="VarChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string ABS
		{
			get
			{
				return this._ABS;
			}
			set
			{
				if ((this._ABS != value))
				{
					this.OnABSChanging(value);
					this.SendPropertyChanging();
					this._ABS = value;
					this.SendPropertyChanged("ABS");
					this.OnABSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousSystem", DbType="VarChar(35)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string PreviousSystem
		{
			get
			{
				return this._PreviousSystem;
			}
			set
			{
				if ((this._PreviousSystem != value))
				{
					this.OnPreviousSystemChanging(value);
					this.SendPropertyChanging();
					this._PreviousSystem = value;
					this.SendPropertyChanged("PreviousSystem");
					this.OnPreviousSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddressLine1", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string PrimaryAddressLine1
		{
			get
			{
				return this._PrimaryAddressLine1;
			}
			set
			{
				if ((this._PrimaryAddressLine1 != value))
				{
					this.OnPrimaryAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._PrimaryAddressLine1 = value;
					this.SendPropertyChanged("PrimaryAddressLine1");
					this.OnPrimaryAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddressLine2", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string PrimaryAddressLine2
		{
			get
			{
				return this._PrimaryAddressLine2;
			}
			set
			{
				if ((this._PrimaryAddressLine2 != value))
				{
					this.OnPrimaryAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._PrimaryAddressLine2 = value;
					this.SendPropertyChanged("PrimaryAddressLine2");
					this.OnPrimaryAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryAddressLine3", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public string PrimaryAddressLine3
		{
			get
			{
				return this._PrimaryAddressLine3;
			}
			set
			{
				if ((this._PrimaryAddressLine3 != value))
				{
					this.OnPrimaryAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._PrimaryAddressLine3 = value;
					this.SendPropertyChanged("PrimaryAddressLine3");
					this.OnPrimaryAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCity", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public string PrimaryCity
		{
			get
			{
				return this._PrimaryCity;
			}
			set
			{
				if ((this._PrimaryCity != value))
				{
					this.OnPrimaryCityChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCity = value;
					this.SendPropertyChanged("PrimaryCity");
					this.OnPrimaryCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryState", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public string PrimaryState
		{
			get
			{
				return this._PrimaryState;
			}
			set
			{
				if ((this._PrimaryState != value))
				{
					this.OnPrimaryStateChanging(value);
					this.SendPropertyChanging();
					this._PrimaryState = value;
					this.SendPropertyChanged("PrimaryState");
					this.OnPrimaryStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryZIP", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public string PrimaryZIP
		{
			get
			{
				return this._PrimaryZIP;
			}
			set
			{
				if ((this._PrimaryZIP != value))
				{
					this.OnPrimaryZIPChanging(value);
					this.SendPropertyChanging();
					this._PrimaryZIP = value;
					this.SendPropertyChanged("PrimaryZIP");
					this.OnPrimaryZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCountry", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public string PrimaryCountry
		{
			get
			{
				return this._PrimaryCountry;
			}
			set
			{
				if ((this._PrimaryCountry != value))
				{
					this.OnPrimaryCountryChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCountry = value;
					this.SendPropertyChanged("PrimaryCountry");
					this.OnPrimaryCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressLine1", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string BillingAddressLine1
		{
			get
			{
				return this._BillingAddressLine1;
			}
			set
			{
				if ((this._BillingAddressLine1 != value))
				{
					this.OnBillingAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._BillingAddressLine1 = value;
					this.SendPropertyChanged("BillingAddressLine1");
					this.OnBillingAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressLine2", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public string BillingAddressLine2
		{
			get
			{
				return this._BillingAddressLine2;
			}
			set
			{
				if ((this._BillingAddressLine2 != value))
				{
					this.OnBillingAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._BillingAddressLine2 = value;
					this.SendPropertyChanged("BillingAddressLine2");
					this.OnBillingAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressLine3", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public string BillingAddressLine3
		{
			get
			{
				return this._BillingAddressLine3;
			}
			set
			{
				if ((this._BillingAddressLine3 != value))
				{
					this.OnBillingAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._BillingAddressLine3 = value;
					this.SendPropertyChanged("BillingAddressLine3");
					this.OnBillingAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCity", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public string BillingCity
		{
			get
			{
				return this._BillingCity;
			}
			set
			{
				if ((this._BillingCity != value))
				{
					this.OnBillingCityChanging(value);
					this.SendPropertyChanging();
					this._BillingCity = value;
					this.SendPropertyChanged("BillingCity");
					this.OnBillingCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingState", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=25)]
		public string BillingState
		{
			get
			{
				return this._BillingState;
			}
			set
			{
				if ((this._BillingState != value))
				{
					this.OnBillingStateChanging(value);
					this.SendPropertyChanging();
					this._BillingState = value;
					this.SendPropertyChanged("BillingState");
					this.OnBillingStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingZIP", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=26)]
		public string BillingZIP
		{
			get
			{
				return this._BillingZIP;
			}
			set
			{
				if ((this._BillingZIP != value))
				{
					this.OnBillingZIPChanging(value);
					this.SendPropertyChanging();
					this._BillingZIP = value;
					this.SendPropertyChanged("BillingZIP");
					this.OnBillingZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCountry", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=27)]
		public string BillingCountry
		{
			get
			{
				return this._BillingCountry;
			}
			set
			{
				if ((this._BillingCountry != value))
				{
					this.OnBillingCountryChanging(value);
					this.SendPropertyChanging();
					this._BillingCountry = value;
					this.SendPropertyChanged("BillingCountry");
					this.OnBillingCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressLine1", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=28)]
		public string ShippingAddressLine1
		{
			get
			{
				return this._ShippingAddressLine1;
			}
			set
			{
				if ((this._ShippingAddressLine1 != value))
				{
					this.OnShippingAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._ShippingAddressLine1 = value;
					this.SendPropertyChanged("ShippingAddressLine1");
					this.OnShippingAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressLine2", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=29)]
		public string ShippingAddressLine2
		{
			get
			{
				return this._ShippingAddressLine2;
			}
			set
			{
				if ((this._ShippingAddressLine2 != value))
				{
					this.OnShippingAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._ShippingAddressLine2 = value;
					this.SendPropertyChanged("ShippingAddressLine2");
					this.OnShippingAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressLine3", DbType="VarChar(200)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=30)]
		public string ShippingAddressLine3
		{
			get
			{
				return this._ShippingAddressLine3;
			}
			set
			{
				if ((this._ShippingAddressLine3 != value))
				{
					this.OnShippingAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._ShippingAddressLine3 = value;
					this.SendPropertyChanged("ShippingAddressLine3");
					this.OnShippingAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingCity", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=31)]
		public string ShippingCity
		{
			get
			{
				return this._ShippingCity;
			}
			set
			{
				if ((this._ShippingCity != value))
				{
					this.OnShippingCityChanging(value);
					this.SendPropertyChanging();
					this._ShippingCity = value;
					this.SendPropertyChanged("ShippingCity");
					this.OnShippingCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingState", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=32)]
		public string ShippingState
		{
			get
			{
				return this._ShippingState;
			}
			set
			{
				if ((this._ShippingState != value))
				{
					this.OnShippingStateChanging(value);
					this.SendPropertyChanging();
					this._ShippingState = value;
					this.SendPropertyChanged("ShippingState");
					this.OnShippingStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingZIP", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=33)]
		public string ShippingZIP
		{
			get
			{
				return this._ShippingZIP;
			}
			set
			{
				if ((this._ShippingZIP != value))
				{
					this.OnShippingZIPChanging(value);
					this.SendPropertyChanging();
					this._ShippingZIP = value;
					this.SendPropertyChanged("ShippingZIP");
					this.OnShippingZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingCountry", DbType="VarChar(40)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=34)]
		public string ShippingCountry
		{
			get
			{
				return this._ShippingCountry;
			}
			set
			{
				if ((this._ShippingCountry != value))
				{
					this.OnShippingCountryChanging(value);
					this.SendPropertyChanging();
					this._ShippingCountry = value;
					this.SendPropertyChanged("ShippingCountry");
					this.OnShippingCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientSinceDateID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=35)]
		public System.Nullable<int> ClientSinceDateID
		{
			get
			{
				return this._ClientSinceDateID;
			}
			set
			{
				if ((this._ClientSinceDateID != value))
				{
					this.OnClientSinceDateIDChanging(value);
					this.SendPropertyChanging();
					this._ClientSinceDateID = value;
					this.SendPropertyChanged("ClientSinceDateID");
					this.OnClientSinceDateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentSiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=36)]
		public System.Nullable<int> ParentSiteID
		{
			get
			{
				return this._ParentSiteID;
			}
			set
			{
				if ((this._ParentSiteID != value))
				{
					this.OnParentSiteIDChanging(value);
					this.SendPropertyChanging();
					this._ParentSiteID = value;
					this.SendPropertyChanged("ParentSiteID");
					this.OnParentSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EBusSiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=37)]
		public System.Nullable<int> EBusSiteID
		{
			get
			{
				return this._EBusSiteID;
			}
			set
			{
				if ((this._EBusSiteID != value))
				{
					this.OnEBusSiteIDChanging(value);
					this.SendPropertyChanging();
					this._EBusSiteID = value;
					this.SendPropertyChanged("EBusSiteID");
					this.OnEBusSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessUnit", DbType="VarChar(100)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=38)]
		public string BusinessUnit
		{
			get
			{
				return this._BusinessUnit;
			}
			set
			{
				if ((this._BusinessUnit != value))
				{
					this.OnBusinessUnitChanging(value);
					this.SendPropertyChanging();
					this._BusinessUnit = value;
					this.SendPropertyChanged("BusinessUnit");
					this.OnBusinessUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bbpsauthenticated", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=39)]
		public System.Nullable<bool> bbpsauthenticated
		{
			get
			{
				return this._bbpsauthenticated;
			}
			set
			{
				if ((this._bbpsauthenticated != value))
				{
					this.OnbbpsauthenticatedChanging(value);
					this.SendPropertyChanging();
					this._bbpsauthenticated = value;
					this.SendPropertyChanged("bbpsauthenticated");
					this.OnbbpsauthenticatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_CASETYPE")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DIM_CASETYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public DIM_CASETYPE()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_USER")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DIM_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LogIn;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _Department;
		
		private System.Nullable<int> _Status;
		
		private string _Supervisor;
		
		private string _FullName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLogInChanging(string value);
    partial void OnLogInChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnSupervisorChanging(string value);
    partial void OnSupervisorChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    #endregion
		
		public DIM_USER()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogIn", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string LogIn
		{
			get
			{
				return this._LogIn;
			}
			set
			{
				if ((this._LogIn != value))
				{
					this.OnLogInChanging(value);
					this.SendPropertyChanging();
					this._LogIn = value;
					this.SendPropertyChanged("LogIn");
					this.OnLogInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(61)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this.OnSupervisorChanging(value);
					this.SendPropertyChanging();
					this._Supervisor = value;
					this.SendPropertyChanged("Supervisor");
					this.OnSupervisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(61)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_CONTACT")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DIM_CONTACT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _FullName;
		
		private string _Phone;
		
		private string _EMail;
		
		private string _Title;
		
		private System.Nullable<int> _DoNotMail;
		
		private System.Nullable<int> _DoNotEMail;
		
		private string _PrimaryRole;
		
		private System.Nullable<int> _PrimarySiteID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDoNotMailChanging(System.Nullable<int> value);
    partial void OnDoNotMailChanged();
    partial void OnDoNotEMailChanging(System.Nullable<int> value);
    partial void OnDoNotEMailChanged();
    partial void OnPrimaryRoleChanging(string value);
    partial void OnPrimaryRoleChanged();
    partial void OnPrimarySiteIDChanging(System.Nullable<int> value);
    partial void OnPrimarySiteIDChanged();
    #endregion
		
		public DIM_CONTACT()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(30)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(61)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNotMail", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> DoNotMail
		{
			get
			{
				return this._DoNotMail;
			}
			set
			{
				if ((this._DoNotMail != value))
				{
					this.OnDoNotMailChanging(value);
					this.SendPropertyChanging();
					this._DoNotMail = value;
					this.SendPropertyChanged("DoNotMail");
					this.OnDoNotMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNotEMail", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> DoNotEMail
		{
			get
			{
				return this._DoNotEMail;
			}
			set
			{
				if ((this._DoNotEMail != value))
				{
					this.OnDoNotEMailChanging(value);
					this.SendPropertyChanging();
					this._DoNotEMail = value;
					this.SendPropertyChanged("DoNotEMail");
					this.OnDoNotEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryRole", DbType="VarChar(80)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string PrimaryRole
		{
			get
			{
				return this._PrimaryRole;
			}
			set
			{
				if ((this._PrimaryRole != value))
				{
					this.OnPrimaryRoleChanging(value);
					this.SendPropertyChanging();
					this._PrimaryRole = value;
					this.SendPropertyChanged("PrimaryRole");
					this.OnPrimaryRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimarySiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> PrimarySiteID
		{
			get
			{
				return this._PrimarySiteID;
			}
			set
			{
				if ((this._PrimarySiteID != value))
				{
					this.OnPrimarySiteIDChanging(value);
					this.SendPropertyChanging();
					this._PrimarySiteID = value;
					this.SendPropertyChanged("PrimarySiteID");
					this.OnPrimarySiteIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
